permalink: /:year/:month/:title
highlighter: "pygments"

production_url: http://teoljungberg.com
title: Teo Ljungberg
description: I love pair-programming, standing desks and beer!
author:
  name: Teo Ljungberg
  email: teo.ljungberg@gmail.com
  github: https://github.com/teoljungberg
  twitter: https://twitter.com/teoljungberg
  linkedin: http://linkedin.com/in/teoljungberg
